config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :blood_glucoses, only: [:index, :new, :create] do
    collection do
      get :this_month_till_date
      get :monthly
      get :custom
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blood_glucose.rb
class BloodGlucose < ApplicationRecord
  belongs_to :user

  validates :value, presence: true, numericality: true
  validates :reading_date, presence: true

  scope :today, -> { where(reading_date: [Time.zone.now.beginning_of_day..Time.zone.now.end_of_day]) }
  scope :this_month_till, -> { where(reading_date: [Time.zone.now.beginning_of_month..Time.zone.now.end_of_day]) }
  scope :by_dates, ->(start_date, end_date) { where(reading_date: [start_date..end_date]) }
end

app/models/user.rb
class User < ApplicationRecord

  has_many :blood_glucoses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_user

  private

  def set_user
    @user = current_user
  end
end

app/controllers/blood_glucoses_controller.rb
class BloodGlucosesController < ApplicationController

  DAILY_QUOTA = 4.freeze

  def index
    @blood_glucoses = @user.blood_glucoses.today
  end

  def new
    @blood_glucose = @user.blood_glucoses.new
  end

  def create
    if @user.blood_glucoses.today.count >= DAILY_QUOTA
      flash[:error] = "Your daily quota #{DAILY_QUOTA} has been reached.  You can not add more entry today"
      redirect_to action: :index
    else
      @blood_glucose = @user.blood_glucoses.new(blood_glucose_params)
      if @blood_glucose.save
        flash[:notice] = 'Blood glucose reading value added successfully'
        redirect_to action: :index
      else
        flash[:error] = 'There is some problem in saving your reading value'
        render action: :create
      end
    end
  end

  def this_month_till_date
    @blood_glucoses = @user.blood_glucoses.this_month_till
  end

  def monthly
    if params[:date].present?
      @selected_month = Date.civil(params[:date][:year].to_i, params[:date][:month].to_i).to_datetime
    else
      @selected_month = Time.zone.now
    end
    @blood_glucoses = @user.blood_glucoses.by_dates(@selected_month.beginning_of_month, @selected_month.end_of_month)
  end

  def custom
    if params[:from].present? && params[:to].present?
      @from = Date.civil(params[:from][:year].to_i, params[:from][:month].to_i, params[:from][:day].to_i).to_datetime
      @to = Date.civil(params[:to][:year].to_i, params[:to][:month].to_i, params[:to][:day].to_i).to_datetime
    else
      @from = Time.zone.now
      @to = Time.zone.now
    end
    @blood_glucoses = @user.blood_glucoses.by_dates(@from.beginning_of_day, @to.end_of_day)
  end

  private

  def blood_glucose_params
    params.require(:blood_glucose).permit(:value, :reading_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blood_glucoses_helper.rb
module BloodGlucosesHelper
end

app/views/blood_glucoses/_list.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Reading date</th>
    <th scope="col">Value</th>
  </tr>
  </thead>
  <tbody>
  <% blood_glucoses.each do |blood_glucose| %>
    <tr>
      <th scope="row"><%= blood_glucose.id %></th>
      <td><%= blood_glucose.reading_date.try(:strftime, '%F') %></td>
      <td><%= blood_glucose.value %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/blood_glucoses/custom.html.erb
<%= link_to 'Add Entry', new_blood_glucose_path, { class: 'btn btn-primary' } %>

<%= form_tag(custom_blood_glucoses_path, method: :get) do |f| %>
  <%= select_date(@from, prefix: 'from') -%>
  <%= select_date(@to, prefix: 'to') -%>
  <%= submit_tag 'Fetch results', { class: 'btn btn-primary' } %>
<% end %>

<%= render partial: 'list', locals: { blood_glucoses: @blood_glucoses } %>

app/views/blood_glucoses/index.html.erb
<%= link_to 'Add Entry', new_blood_glucose_path, { class: 'btn btn-primary' } %>
<%= render partial: 'list', locals: { blood_glucoses: @blood_glucoses } %>

app/views/blood_glucoses/monthly.html.erb
<%= link_to 'Add Entry', new_blood_glucose_path, { class: 'btn btn-primary' } %>

<%= form_tag(monthly_blood_glucoses_path, method: :get) do |f| %>
  <%= select_month(@selected_month) %>
  <%= select_year(@selected_month) %>
  <%= submit_tag 'Fetch results', { class: 'btn btn-primary' } %>
<% end %>

<%= render partial: 'list', locals: { blood_glucoses: @blood_glucoses } %>

app/views/blood_glucoses/new.html.erb
<%= form_with model: @blood_glucose do |f| %>
  <div class="form-group mb-2">
    <label for="exampleInputEmail1">Glucose value</label>
    <%= f.number_field :value, { class: 'form-control', required: true } %>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Reading date</label>
    <%= f.date_select :reading_date, { class: 'form-control' } %>
  </div>
  <%= f.submit 'Add Entry', { class: 'btn btn-primary' } %>
<% end %>

app/views/blood_glucoses/this_month_till_date.html.erb
<%= link_to 'Add Entry', new_blood_glucose_path, { class: 'btn btn-primary' } %>
<%= render partial: 'list', locals: { blood_glucoses: @blood_glucoses } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sweety</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Blood Glucose', blood_glucoses_path, { class: 'nav-link' } -%>
        </li>
        <li class="nav-item">
          <%= link_to 'This month till now', this_month_till_date_blood_glucoses_path, { class: 'nav-link' } -%>
        </li>
        <li class="nav-item">
          <%= link_to 'Monthly', monthly_blood_glucoses_path, { class: 'nav-link' } -%>
        </li>
        <li class="nav-item">
          <%= link_to 'Custom', custom_blood_glucoses_path, { class: 'nav-link' } -%>
        </li>

      </ul>
      <div class="my-2 my-lg-0">
        <label><%= @user.email %></label>
      </div>
    </div>
  </nav>
  <p class="notice"><%= flash[:notice] %></p>
  <p class="error"><%= flash[:error] %></p>
    <%= yield %>
  </body>
</html>